### ISSUE TITLE
Support des listes 

### ISSUE THREAD

**Issue by jsamr** [Frosty-Z/dirtylab-site-scripts#4]
Je ne sais pas si l'outil utilisé supporte du github flavoured markdown, mais il n'a pas l'air de bien gérer les listes à puce dans certains cas, exemple : http://dirtylab.github.io/DEFINITIONS.html#f-ontologie (les puces sont à l'intérieur d'un blockquote).

**Comment by mpacary** [comment]
J'ai modifié le Markdown d'origine pour contourner le problème, pas possible de faire mieux (je passe par un moteur de rendu Markdown "redcarpet" censé faire la même chose que GitHub, mais sur lequel je n'ai pas la main :cry: )

La "correction" est en ligne => je ferme
